version: '3.8'

services:
  todo-cli:
    build: .
    image: todo-cli:latest
    container_name: todo-app
    stdin_open: true
    tty: true
    volumes:
      - ./data:/app/data
    restart: unless-stopped